import type {
  ActivityItem,
  AgentTraceStep,
  AuditEvent,
  DeskComment,
  EvalCase,
  Incident,
  PushNote,
  Role,
  SourceHealth,
  Ticket,
} from "./types";

const T0 = new Date("2026-08-13T01:05:00+05:30").getTime();

export function ago(mins: number): string {
  return new Date(T0 - mins * 60_000).toISOString();
}

export const ROLES: Role[] = [
  { id: "oncall", name: "Priya Mehta", title: "On-call · Mobile Security", initials: "PM" },
  { id: "manager", name: "Arjun Shah", title: "Eng Manager · Apps", initials: "AS" },
  { id: "triage", name: "Kavya Iyer", title: "Triage · Support", initials: "KI" },
  { id: "operator", name: "Rohan Desai", title: "FDE Operator", initials: "RD" },
];

function doneTrace(overrides?: Partial<Record<AgentTraceStep["id"], string>>): AgentTraceStep[] {
  const steps: AgentTraceStep[] = [
    { id: "ingest", label: "Ingest", status: "ok", detail: "Normalized payload", ms: 41 },
    { id: "embed", label: "Embed", status: "ok", detail: "bge-small · 384d", ms: 118 },
    { id: "retrieve", label: "Retrieve similar", status: "ok", detail: overrides?.retrieve ?? "3 neighbors", ms: 206 },
    { id: "classify", label: "Classify", status: "ok", detail: overrides?.classify ?? "crash · payment", ms: 642 },
    { id: "prioritize", label: "Prioritize", status: "ok", detail: overrides?.prioritize ?? "blast scored", ms: 74 },
    { id: "draft_fix", label: "Draft fix", status: "ok", detail: "Patch + rationale", ms: 811 },
    { id: "draft_ticket", label: "Draft ticket", status: "ok", detail: "Linear payload", ms: 288 },
    { id: "hitl", label: "HITL interrupt", status: "wait", detail: "Write blocked until approval" },
  ];
  return steps;
}

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: "INC-1842",
    source: "crashlytics",
    kind: "crash",
    title: "Null check operator used on a null value in UpiCollectSheet",
    summary:
      "Flutter consumer crash after banks list returns empty from /v3/upi/banks. Spiked 18 minutes after 4.18.2 rolled to 42% of Android.",
    raw: `FlutterError: Null check operator used on a null value
#0  UpiCollectSheetState._selectDefaultBank (upi_collect_sheet.dart:214)
#1  UpiCollectSheetState._onBanksLoaded (upi_collect_sheet.dart:167)
#2  _RootZone.runUnary (dart:async)
app: nivapay 4.18.2 (build 41820)
os: Android 14 · SM-A156B · 42% of 4.18.2 Android cohort
first_seen: 2026-08-12T23:41:12+05:30
sessions_affected: 14280
breadcrumb: GET https://api.nivapay.in/v3/upi/banks → 200 { "banks": [] }`,
    app: "consumer",
    appVersion: "4.18.2",
    platform: "android",
    deviceHint: "Galaxy A15 · Android 14",
    severity: "P0",
    blastRadius: 86,
    affectedUsers: 14280,
    occurrences: 31844,
    confidence: 0.93,
    status: "awaiting_approval",
    classification: "Crash · payment collect · null-safety regression",
    suggestedFix:
      "Guard empty bank list before selecting a default. Show an empty-state with retry instead of force-unwrapping banks.first. Gate 4.18.2 roll-out at 42%.",
    suggestedPatch: `if (banks.isEmpty) {
  setState(() => _emptyBanks = true);
  _analytics.track('upi_banks_empty');
  return;
}
final bank = banks.first;`,
    similarIssues: [
      {
        id: "INC-1611",
        ticketKey: "MOBILE-3618",
        title: "Empty IFSC list NPE on add-beneficiary",
        resolution: "Null-safe empty state + retry; rolled back 3.9.4.",
        similarity: 0.91,
        closedAt: ago(60 * 24 * 46),
      },
      {
        id: "INC-1544",
        ticketKey: "MOBILE-3480",
        title: "UPI intent null after NPCI timeout",
        resolution: "Timeout treated as empty result, not crash.",
        similarity: 0.74,
        closedAt: ago(60 * 24 * 71),
      },
    ],
    draftTicket: {
      project: "MOBILE",
      keyPreview: "MOBILE-4091",
      title: "[P0] Guard empty bank list in UpiCollectSheet (4.18.2 Android)",
      description:
        "Crashlytics spike: 14.2k users, 31k events after 4.18.2. /v3/upi/banks returned []. Force unwrap at upi_collect_sheet.dart:214.\n\nAsk: pause staged rollout, ship empty-state guard, add contract test for empty banks payload.",
      labels: ["crash", "upi", "android", "p0", "regression"],
      assignee: "meera.kapoor",
      priority: "P0",
    },
    trace: doneTrace({
      classify: "crash · payment · null-safety",
      prioritize: "blast 86 · 14.2k users",
      retrieve: "INC-1611 91% · INC-1544 74%",
    }),
    createdAt: ago(24),
    updatedAt: ago(18),
    tags: ["upi", "rollout", "android"],
  },
  {
    id: "INC-1841",
    source: "sentry",
    kind: "crash",
    title: "ANR: CameraX deadlock in merchant QR scanner",
    summary:
      "NivaBiz RN ANR when torch + scan run together on mid-range MediaTek devices. Correlates with a 1-star review cluster.",
    raw: `ANR in com.nivapay.biz
Reason: Input dispatching timed out (Waiting to send non-key event)
Trace:
  at jdk.internal.misc.Unsafe.park(Native)
  at androidx.camera.core.impl.utils.executor.HandlerScheduledExecutorService
  at com.nivapay.biz.scan.QrScanModule.startTorch (QrScanModule.kt:88)
sessions: 2140
devices: moto g54, Redmi Note 13, vivo T3x (MediaTek Dimensity)
app: nivabiz 2.9.1`,
    app: "merchant",
    appVersion: "2.9.1",
    platform: "android",
    deviceHint: "MediaTek mid-range",
    severity: "P1",
    blastRadius: 61,
    affectedUsers: 2140,
    occurrences: 4902,
    confidence: 0.88,
    status: "awaiting_approval",
    classification: "ANR · camera · merchant scan",
    suggestedFix:
      "Serialize torch enable onto the CameraX main executor and drop the second bindToLifecycle call. Add ANR breadcrumb around torch toggle.",
    suggestedPatch: `cameraExecutor.execute {
  if (!torchBound) {
    camera.cameraControl.enableTorch(enabled)
    torchBound = true
  }
}`,
    similarIssues: [
      {
        id: "INC-1702",
        ticketKey: "MOBILE-3820",
        title: "Camera freeze on first scan after permission grant",
        resolution: "Rebound use-case once; removed duplicate preview.",
        similarity: 0.69,
        closedAt: ago(60 * 24 * 21),
      },
    ],
    draftTicket: {
      project: "MOBILE",
      keyPreview: "MOBILE-4090",
      title: "[P1] Fix CameraX ANR on torch toggle — NivaBiz 2.9.1",
      description:
        "Sentry ANR, 2.1k merchants, clustered on MediaTek. Torch + scan double-bind. Reviews mention 'app freeze jab QR scan karta hoon'.",
      labels: ["anr", "camera", "merchant", "android"],
      assignee: "dev.iyer",
      priority: "P1",
    },
    trace: doneTrace({
      classify: "anr · camera",
      prioritize: "blast 61 · merchant GMV at risk",
    }),
    createdAt: ago(48),
    updatedAt: ago(31),
    tags: ["camera", "anr", "reviews"],
  },
  {
    id: "INC-1839",
    source: "snyk",
    kind: "vuln",
    title: "Hardcoded Razorpay live key shipped in NivaBiz JS bundle",
    summary:
      "Snyk code scan on main found rzp_live_* in src/config/payments.ts. Bundle is public in the Play download.",
    raw: `{
  "tool": "snyk-code",
  "rule": "HardcodedSecret",
  "severity": "critical",
  "file": "src/config/payments.ts",
  "line": 17,
  "snippet": "export const RZP_KEY = 'rzp_live_9kQ••••••••';",
  "repo": "nivapay/nivabiz-app",
  "commit": "a91c3e2",
  "introduced_in": "2.8.0"
}`,
    app: "merchant",
    appVersion: "2.9.1",
    platform: "both",
    severity: "P0",
    blastRadius: 94,
    affectedUsers: 0,
    occurrences: 1,
    confidence: 0.97,
    status: "awaiting_approval",
    classification: "Secret exposure · payments · public bundle",
    suggestedFix:
      "Rotate the Razorpay live key immediately. Remove from source, load from remote config, add gitleaks + CI secret scan. Treat as a security incident — do not wait for the next store release to rotate.",
    suggestedPatch: `// payments.ts
export const RZP_KEY = remoteConfig.getString('rzp_key');
// CI: gitleaks protect --staged`,
    similarIssues: [
      {
        id: "INC-1320",
        ticketKey: "SEC-884",
        title: "Firebase API key committed to consumer app",
        resolution: "Rotated, moved to remote config, added gitleaks.",
        similarity: 0.84,
        closedAt: ago(60 * 24 * 120),
      },
    ],
    draftTicket: {
      project: "SEC",
      keyPreview: "SEC-1402",
      title: "[P0] Rotate Razorpay live key leaked in NivaBiz bundle",
      description:
        "Snyk HardcodedSecret on payments.ts:17. Key is in the public RN bundle.\n\nRunbook: rotate RZP live key → invalidate old → ship remote-config fetch → postmortem. Notify payments + compliance.",
      labels: ["secret", "p0", "compliance", "snyk"],
      assignee: "priya.mehta",
      priority: "P0",
    },
    trace: doneTrace({
      classify: "vuln · secret · critical",
      prioritize: "blast 94 · rotate now",
      retrieve: "SEC-884 84%",
    }),
    createdAt: ago(71),
    updatedAt: ago(55),
    tags: ["secret", "payments", "compliance"],
  },
  {
    id: "INC-1834",
    source: "sentry",
    kind: "crash",
    title: "Keyboard covers Aadhaar OTP field on small Androids",
    summary: "KYC drop-off + 180 Sentry breadcrumbs. Not a crash — UX defect with measurable conversion hit.",
    raw: `Sentry: ui.dead_click  on #aadhaar-otp
screen: KycAadhaarOtp
inset_bottom: 0 (keyboard overlay, adjustResize missing)
affected: 5.2"–6.0" Android, 180 sessions / 12h
funnel: KYC start → OTP 41% drop (was 18%)`,
    app: "consumer",
    appVersion: "4.18.1",
    platform: "android",
    deviceHint: "≤6.0\" Android",
    severity: "P2",
    blastRadius: 38,
    affectedUsers: 180,
    occurrences: 180,
    confidence: 0.81,
    status: "awaiting_approval",
    classification: "UX defect · KYC · keyboard inset",
    suggestedFix:
      "Set windowSoftInputMode=adjustResize on KycActivity and wrap the OTP field in a KeyboardAvoidingView. Add detox case for 540px-tall emulator.",
    suggestedPatch: `android:windowSoftInputMode="adjustResize"
// Flutter
resizeToAvoidBottomInset: true`,
    similarIssues: [],
    draftTicket: {
      project: "MOBILE",
      keyPreview: "MOBILE-4086",
      title: "[P2] KYC OTP field hidden by keyboard on small Android",
      description: "Conversion drop 18% → 41% at Aadhaar OTP. Inset not applied.",
      labels: ["kyc", "android", "ux"],
      assignee: "aisha.khan",
      priority: "P2",
    },
    trace: doneTrace({ classify: "ux · kyc", prioritize: "blast 38" }),
    createdAt: ago(140),
    updatedAt: ago(90),
    tags: ["kyc", "conversion"],
  },
  {
    id: "INC-1820",
    source: "play_reviews",
    kind: "review",
    title: "Review cluster: payment deducted twice, no refund",
    summary:
      "47 one-star reviews in 36 hours, Hindi + English. Ledger team confirms a webhook retry bug on collect success.",
    raw: `"Paise kat gaye do baar, refund nahi aaya. Order #NP88211."
"Debited twice for the same UPI collect. Chat support useless."
cluster_size: 47
rating_avg_24h: 2.1 (was 4.3)
linked_backend: payments-webhook-retry (already P1 on API side)`,
    app: "consumer",
    appVersion: "4.18.2",
    platform: "android",
    severity: "P1",
    blastRadius: 72,
    affectedUsers: 47,
    occurrences: 47,
    confidence: 0.79,
    status: "awaiting_approval",
    classification: "Review cluster · payments · double debit",
    suggestedFix:
      "Do not treat this as a client crash. Open a SUPPORT ticket linking the existing payments webhook P1. Draft a Play reply template and pause 4.18.2 store listing experiments.",
    similarIssues: [
      {
        id: "INC-1488",
        ticketKey: "SUPPORT-2201",
        title: "Double debit cluster after NPCI timeout (2025)",
        resolution: "Idempotency key on webhook + Play reply playbook.",
        similarity: 0.88,
        closedAt: ago(60 * 24 * 88),
      },
    ],
    draftTicket: {
      project: "SUPPORT",
      keyPreview: "SUPPORT-3114",
      title: "[P1] Play review cluster — double UPI debit (47 reviews)",
      description:
        "Link to payments webhook retry P1. Reply template + refund sweep for cluster IDs. Client is not at fault.",
      labels: ["reviews", "payments", "reputation"],
      assignee: "kavya.iyer",
      priority: "P1",
    },
    trace: doneTrace({
      classify: "review · payments",
      retrieve: "SUPPORT-2201 88%",
    }),
    createdAt: ago(210),
    updatedAt: ago(160),
    tags: ["reviews", "payments"],
  },
  {
    id: "INC-1843",
    source: "crashlytics",
    kind: "crash",
    title: "EXC_BAD_ACCESS in BiometricUnlock on iOS 18.6",
    summary: "Just landed. Agent is still running the graph.",
    raw: `Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Thread 0 Crashed:
0  libswiftCore.dylib
1  NivaPay.BiometricUnlock.start (BiometricUnlock.swift:91)
app: 4.18.2 (iOS)
count: 126 so far, climbing`,
    app: "consumer",
    appVersion: "4.18.2",
    platform: "ios",
    deviceHint: "iPhone 15 / 16 · iOS 18.6",
    severity: "P1",
    blastRadius: 0,
    affectedUsers: 126,
    occurrences: 126,
    confidence: 0,
    status: "ingested",
    classification: "",
    suggestedFix: "",
    similarIssues: [],
    draftTicket: {
      project: "MOBILE",
      keyPreview: "MOBILE-4092",
      title: "",
      description: "",
      labels: [],
      assignee: "meera.kapoor",
      priority: "P1",
    },
    trace: [
      { id: "ingest", label: "Ingest", status: "ok", detail: "Crashlytics export", ms: 38 },
      { id: "embed", label: "Embed", status: "pending", detail: "Queued" },
      { id: "retrieve", label: "Retrieve similar", status: "pending", detail: "" },
      { id: "classify", label: "Classify", status: "pending", detail: "" },
      { id: "prioritize", label: "Prioritize", status: "pending", detail: "" },
      { id: "draft_fix", label: "Draft fix", status: "pending", detail: "" },
      { id: "draft_ticket", label: "Draft ticket", status: "pending", detail: "" },
      { id: "hitl", label: "HITL interrupt", status: "pending", detail: "" },
    ],
    createdAt: ago(6),
    updatedAt: ago(6),
    tags: ["ios", "biometric"],
  },
  {
    id: "INC-1837",
    source: "sentry",
    kind: "crash",
    title: "TLS handshake failed after api.nivapay.in cert rotation",
    summary: "Pinned cert mismatch. Ticket already filed and in progress.",
    raw: `javax.net.ssl.SSLHandshakeException: Certificate pinning failure
Pin set did not match leaf of api.nivapay.in
app: 4.17.9–4.18.1`,
    app: "consumer",
    appVersion: "4.18.1",
    platform: "both",
    severity: "P1",
    blastRadius: 70,
    affectedUsers: 890,
    occurrences: 4100,
    confidence: 0.95,
    status: "ticketed",
    classification: "Network · cert pin · config",
    suggestedFix: "Ship updated pins via remote config; never bake the next leaf into the binary.",
    similarIssues: [],
    draftTicket: {
      project: "MOBILE",
      keyPreview: "MOBILE-4078",
      title: "[P1] Update TLS pins after cert rotation",
      description: "Pin mismatch after rotation window.",
      labels: ["tls", "network"],
      assignee: "dev.iyer",
      priority: "P1",
    },
    trace: doneTrace({ classify: "network · tls" }),
    createdAt: ago(60 * 9),
    updatedAt: ago(60 * 7),
    tags: ["tls"],
    ticketKey: "MOBILE-4078",
    approvedBy: "Priya Mehta",
  },
  {
    id: "INC-1828",
    source: "snyk",
    kind: "vuln",
    title: "okhttp 4.10.0 — CVE-2023-47818 (fixed in 4.12.0)",
    summary: "Transitive via the payments SDK. Ticketed yesterday.",
    raw: `{ "cve": "CVE-2023-47818", "package": "com.squareup.okhttp3:okhttp", "version": "4.10.0" }`,
    app: "merchant",
    appVersion: "2.9.1",
    platform: "android",
    severity: "P2",
    blastRadius: 40,
    affectedUsers: 0,
    occurrences: 1,
    confidence: 0.9,
    status: "ticketed",
    classification: "Dependency · CVE",
    suggestedFix: "Bump okhttp to 4.12.2 and force resolution in Gradle.",
    similarIssues: [],
    draftTicket: {
      project: "SEC",
      keyPreview: "SEC-1394",
      title: "[P2] Bump okhttp past CVE-2023-47818",
      description: "Force 4.12.2.",
      labels: ["snyk", "deps"],
      assignee: "priya.mehta",
      priority: "P2",
    },
    trace: doneTrace({ classify: "vuln · dep" }),
    createdAt: ago(60 * 20),
    updatedAt: ago(60 * 16),
    tags: ["deps"],
    ticketKey: "SEC-1394",
    approvedBy: "Priya Mehta",
  },
  {
    id: "INC-1811",
    source: "snyk",
    kind: "vuln",
    title: "Help-center WebView exposes JavascriptInterface",
    summary: "addJavascriptInterface on a WebView that also loads remote help articles.",
    raw: `file: HelpWebView.kt:44
addJavascriptInterface(Bridge(), "Niva")`,
    app: "consumer",
    appVersion: "4.18.0",
    platform: "android",
    severity: "P1",
    blastRadius: 55,
    affectedUsers: 0,
    occurrences: 1,
    confidence: 0.86,
    status: "ticketed",
    classification: "Vuln · webview · js-bridge",
    suggestedFix: "Remove the bridge; use shouldOverrideUrlLoading for known deep links only.",
    similarIssues: [],
    draftTicket: {
      project: "SEC",
      keyPreview: "SEC-1388",
      title: "[P1] Remove JS bridge from help WebView",
      description: "Remote content + JavascriptInterface.",
      labels: ["webview", "android"],
      assignee: "priya.mehta",
      priority: "P1",
    },
    trace: doneTrace({ classify: "vuln · webview" }),
    createdAt: ago(60 * 36),
    updatedAt: ago(60 * 30),
    tags: ["webview"],
    ticketKey: "SEC-1388",
    approvedBy: "Arjun Shah",
  },
  {
    id: "INC-1804",
    source: "snyk",
    kind: "vuln",
    title: "READ_SMS leftover after OTP auto-read removal",
    summary: "Play policy risk. Ticketed; waiting on store release.",
    raw: `AndroidManifest.xml still declares READ_SMS, RECEIVE_SMS`,
    app: "consumer",
    appVersion: "4.18.2",
    platform: "android",
    severity: "P2",
    blastRadius: 30,
    affectedUsers: 0,
    occurrences: 1,
    confidence: 0.92,
    status: "ticketed",
    classification: "Policy · permissions",
    suggestedFix: "Drop the permissions and the unused SmsReceiver.",
    similarIssues: [],
    draftTicket: {
      project: "MOBILE",
      keyPreview: "MOBILE-4051",
      title: "[P2] Remove leftover SMS permissions",
      description: "Policy risk on next Play review.",
      labels: ["permissions", "play"],
      assignee: "aisha.khan",
      priority: "P2",
    },
    trace: doneTrace({ classify: "policy · sms" }),
    createdAt: ago(60 * 50),
    updatedAt: ago(60 * 40),
    tags: ["permissions"],
    ticketKey: "MOBILE-4051",
    approvedBy: "Arjun Shah",
  },
  {
    id: "INC-1824",
    source: "crashlytics",
    kind: "crash",
    title: "Index out of range in RewardsCarousel",
    summary: "Rare. Human rejected — noise, already fixed in 4.18.3 unreleased.",
    raw: `RangeError (index): Invalid value: 3, length 3
rewards_carousel.dart:58`,
    app: "consumer",
    appVersion: "4.17.9",
    platform: "ios",
    severity: "P3",
    blastRadius: 8,
    affectedUsers: 22,
    occurrences: 40,
    confidence: 0.54,
    status: "rejected",
    classification: "Crash · rewards · already-fixed",
    suggestedFix: "Ignore. Fix is on 4.18.3.",
    similarIssues: [],
    draftTicket: {
      project: "MOBILE",
      keyPreview: "MOBILE-4071",
      title: "[P3] RewardsCarousel OOB",
      description: "Already on 4.18.3.",
      labels: ["rewards"],
      assignee: "aisha.khan",
      priority: "P3",
    },
    trace: doneTrace({ classify: "crash · low" }),
    createdAt: ago(60 * 28),
    updatedAt: ago(60 * 26),
    tags: ["rewards"],
    rejectReason: "Already fixed on 4.18.3. Do not open a duplicate ticket.",
  },
  {
    id: "INC-1798",
    source: "appstore",
    kind: "review",
    title: "OTP arrives late after 4.18 — 12 reviews",
    summary: "Likely SMS provider, not client. Sitting in inbox for triage.",
    raw: `"OTP aane mein 5 minute. Pehle instant tha."`,
    app: "consumer",
    appVersion: "4.18.0",
    platform: "ios",
    severity: "P3",
    blastRadius: 18,
    affectedUsers: 12,
    occurrences: 12,
    confidence: 0.62,
    status: "ingested",
    classification: "",
    suggestedFix: "",
    similarIssues: [],
    draftTicket: {
      project: "SUPPORT",
      keyPreview: "SUPPORT-3108",
      title: "",
      description: "",
      labels: [],
      assignee: "kavya.iyer",
      priority: "P3",
    },
    trace: [
      { id: "ingest", label: "Ingest", status: "ok", detail: "App Store RSS", ms: 52 },
      { id: "embed", label: "Embed", status: "pending", detail: "Queued" },
      { id: "retrieve", label: "Retrieve similar", status: "pending", detail: "" },
      { id: "classify", label: "Classify", status: "pending", detail: "" },
      { id: "prioritize", label: "Prioritize", status: "pending", detail: "" },
      { id: "draft_fix", label: "Draft fix", status: "pending", detail: "" },
      { id: "draft_ticket", label: "Draft ticket", status: "pending", detail: "" },
      { id: "hitl", label: "HITL interrupt", status: "pending", detail: "" },
    ],
    createdAt: ago(60 * 60),
    updatedAt: ago(60 * 60),
    tags: ["otp", "reviews"],
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    key: "MOBILE-4078",
    incidentId: "INC-1837",
    project: "MOBILE",
    title: "[P1] Update TLS pins after cert rotation",
    status: "in_progress",
    priority: "P1",
    assignee: "dev.iyer",
    labels: ["tls", "network"],
    createdAt: ago(60 * 7),
    url: "#",
  },
  {
    key: "SEC-1394",
    incidentId: "INC-1828",
    project: "SEC",
    title: "[P2] Bump okhttp past CVE-2023-47818",
    status: "todo",
    priority: "P2",
    assignee: "priya.mehta",
    labels: ["snyk", "deps"],
    createdAt: ago(60 * 16),
    url: "#",
  },
  {
    key: "SEC-1388",
    incidentId: "INC-1811",
    project: "SEC",
    title: "[P1] Remove JS bridge from help WebView",
    status: "in_progress",
    priority: "P1",
    assignee: "priya.mehta",
    labels: ["webview", "android"],
    createdAt: ago(60 * 30),
    url: "#",
  },
  {
    key: "MOBILE-4051",
    incidentId: "INC-1804",
    project: "MOBILE",
    title: "[P2] Remove leftover SMS permissions",
    status: "todo",
    priority: "P2",
    assignee: "aisha.khan",
    labels: ["permissions", "play"],
    createdAt: ago(60 * 40),
    url: "#",
  },
  {
    key: "MOBILE-3990",
    incidentId: "INC-1611",
    project: "MOBILE",
    title: "[P1] Empty IFSC list NPE — add-beneficiary",
    status: "done",
    priority: "P1",
    assignee: "meera.kapoor",
    labels: ["crash"],
    createdAt: ago(60 * 24 * 46),
    url: "#",
  },
];

export const INITIAL_AUDIT: AuditEvent[] = [
  {
    id: "aud-1",
    ts: ago(6),
    actor: "agent",
    action: "ingest",
    incidentId: "INC-1843",
    detail: "Crashlytics export accepted · 126 events",
  },
  {
    id: "aud-2",
    ts: ago(18),
    actor: "agent",
    action: "draft_ticket",
    incidentId: "INC-1842",
    detail: "HITL interrupt · MOBILE-4091 ready",
  },
  {
    id: "aud-3",
    ts: ago(31),
    actor: "agent",
    action: "draft_ticket",
    incidentId: "INC-1841",
    detail: "HITL interrupt · MOBILE-4090 ready",
  },
  {
    id: "aud-4",
    ts: ago(55),
    actor: "agent",
    action: "draft_ticket",
    incidentId: "INC-1839",
    detail: "Secret finding · SEC-1402 ready · write blocked",
  },
  {
    id: "aud-5",
    ts: ago(60 * 7),
    actor: "Priya Mehta",
    action: "approve",
    incidentId: "INC-1837",
    detail: "Created MOBILE-4078",
  },
  {
    id: "aud-6",
    ts: ago(60 * 16),
    actor: "Priya Mehta",
    action: "approve",
    incidentId: "INC-1828",
    detail: "Created SEC-1394",
  },
  {
    id: "aud-7",
    ts: ago(60 * 26),
    actor: "Arjun Shah",
    action: "reject",
    incidentId: "INC-1824",
    detail: "Already fixed on 4.18.3",
  },
  {
    id: "aud-8",
    ts: ago(60 * 30),
    actor: "Arjun Shah",
    action: "approve",
    incidentId: "INC-1811",
    detail: "Created SEC-1388",
  },
  {
    id: "aud-9",
    ts: ago(60 * 40),
    actor: "Priya Mehta",
    action: "approve",
    incidentId: "INC-1804",
    detail: "Created MOBILE-4051",
  },
  {
    id: "aud-10",
    ts: ago(90),
    actor: "agent",
    action: "classify",
    incidentId: "INC-1834",
    detail: "P2 · KYC keyboard inset · 0.81 confidence",
  },
];

export const INITIAL_EVALS: EvalCase[] = [
  { id: "e1", name: "Empty bank list NPE", source: "crashlytics", expectedSeverity: "P0", predictedSeverity: "P0", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: true, latencyMs: 1840 },
  { id: "e2", name: "Hardcoded RZP key", source: "snyk", expectedSeverity: "P0", predictedSeverity: "P0", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: null, latencyMs: 2104 },
  { id: "e3", name: "CameraX ANR", source: "sentry", expectedSeverity: "P1", predictedSeverity: "P1", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: null, latencyMs: 1766 },
  { id: "e4", name: "Rewards OOB (already fixed)", source: "crashlytics", expectedSeverity: "P3", predictedSeverity: "P3", expectedAction: "ignore", predictedAction: "ticket", humanAccepted: false, latencyMs: 1540 },
  { id: "e5", name: "Double-debit review cluster", source: "play_reviews", expectedSeverity: "P1", predictedSeverity: "P1", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: null, latencyMs: 1988 },
  { id: "e6", name: "TLS pin mismatch", source: "sentry", expectedSeverity: "P1", predictedSeverity: "P1", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: true, latencyMs: 1422 },
  { id: "e7", name: "okhttp CVE", source: "snyk", expectedSeverity: "P2", predictedSeverity: "P2", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: true, latencyMs: 990 },
  { id: "e8", name: "WebView JS bridge", source: "snyk", expectedSeverity: "P1", predictedSeverity: "P1", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: true, latencyMs: 1210 },
  { id: "e9", name: "READ_SMS leftover", source: "snyk", expectedSeverity: "P2", predictedSeverity: "P2", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: true, latencyMs: 870 },
  { id: "e10", name: "KYC keyboard", source: "sentry", expectedSeverity: "P2", predictedSeverity: "P2", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: null, latencyMs: 1604 },
  { id: "e11", name: "OTP late reviews", source: "appstore", expectedSeverity: "P3", predictedSeverity: "P3", expectedAction: "escalate", predictedAction: "ticket", humanAccepted: null, latencyMs: 2011 },
  { id: "e12", name: "Biometric iOS EXC_BAD_ACCESS", source: "crashlytics", expectedSeverity: "P1", predictedSeverity: "P1", expectedAction: "ticket", predictedAction: "ticket", humanAccepted: null, latencyMs: 0 },
];

export const INITIAL_SOURCES: SourceHealth[] = [
  { id: "crashlytics", label: "Firebase Crashlytics", lastPullAt: ago(4), events24h: 36112, status: "healthy", note: "Export + webhook" },
  { id: "sentry", label: "Sentry", lastPullAt: ago(3), events24h: 5408, status: "healthy", note: "Issues API" },
  { id: "snyk", label: "Snyk Code + Open Source", lastPullAt: ago(22), events24h: 6, status: "healthy", note: "CI SARIF on main" },
  { id: "play_reviews", label: "Play Console reviews", lastPullAt: ago(12), events24h: 61, status: "degraded", note: "Quota 80% · backoff" },
  { id: "appstore", label: "App Store Connect", lastPullAt: ago(18), events24h: 14, status: "healthy", note: "RSS + Connect API" },
  { id: "manual", label: "Paste / file upload", lastPullAt: ago(0), events24h: 0, status: "healthy", note: "On-call drop zone" },
];

export const INITIAL_ACTIVITY: ActivityItem[] = [
  { id: "act-1", ts: ago(6), text: "Ingested INC-1843 from Crashlytics · graph started", tone: "warn" },
  { id: "act-2", ts: ago(18), text: "INC-1842 drafted · HITL waiting on Priya", tone: "neutral" },
  { id: "act-3", ts: ago(31), text: "INC-1841 drafted · merchant ANR", tone: "neutral" },
  { id: "act-4", ts: ago(55), text: "INC-1839 secret finding · write blocked", tone: "danger" },
  { id: "act-5", ts: ago(60 * 7), text: "Priya approved INC-1837 → MOBILE-4078", tone: "ok" },
];

export const INITIAL_NOTES: PushNote[] = [
  {
    id: "n1",
    title: "P0 waiting on you",
    body: "Empty bank list crash · 14.2k users · 4.18.2 Android",
    incidentId: "INC-1842",
    ts: ago(18),
    read: false,
  },
  {
    id: "n2",
    title: "Secret exposure",
    body: "Razorpay live key in NivaBiz bundle. Rotate before ticket.",
    incidentId: "INC-1839",
    ts: ago(55),
    read: false,
  },
];

export const CRASH_14D = [
  { d: "Jul 31", n: 420 },
  { d: "Aug 1", n: 390 },
  { d: "Aug 2", n: 410 },
  { d: "Aug 3", n: 455 },
  { d: "Aug 4", n: 480 },
  { d: "Aug 5", n: 440 },
  { d: "Aug 6", n: 510 },
  { d: "Aug 7", n: 495 },
  { d: "Aug 8", n: 530 },
  { d: "Aug 9", n: 560 },
  { d: "Aug 10", n: 610 },
  { d: "Aug 11", n: 780 },
  { d: "Aug 12", n: 1420 },
  { d: "Aug 13", n: 980 },
];

export const ACCEPT_14D = [
  { d: "Jul 31", pct: 68 },
  { d: "Aug 1", pct: 70 },
  { d: "Aug 2", pct: 69 },
  { d: "Aug 3", pct: 71 },
  { d: "Aug 4", pct: 73 },
  { d: "Aug 5", pct: 72 },
  { d: "Aug 6", pct: 74 },
  { d: "Aug 7", pct: 75 },
  { d: "Aug 8", pct: 73 },
  { d: "Aug 9", pct: 76 },
  { d: "Aug 10", pct: 74 },
  { d: "Aug 11", pct: 72 },
  { d: "Aug 12", pct: 74 },
  { d: "Aug 13", pct: 74 },
];

export const INITIAL_COMMENTS: DeskComment[] = [
  {
    id: "c1",
    incidentId: "INC-1842",
    author: "Meera Kapoor",
    body: "Confirmed empty banks payload in staging against HDFC. Rolling back 4.18.2 Android past 20% until the guard lands.",
    ts: ago(16),
  },
  {
    id: "c2",
    incidentId: "INC-1842",
    author: "Priya Mehta",
    body: "Hold the ticket assignee as Meera. Payments wants a postmortem if this crosses 20k users.",
    ts: ago(12),
  },
  {
    id: "c3",
    incidentId: "INC-1839",
    author: "Rohan Desai",
    body: "Do not wait for a store release. Rotate the Razorpay key in the dashboard first, then ship the remote-config change.",
    ts: ago(40),
  },
  {
    id: "c4",
    incidentId: "INC-1820",
    author: "Kavya Iyer",
    body: "Refund sweep started for the 47 review cluster. Need the SUPPORT ticket before I reply on Play.",
    ts: ago(150),
  },
];

