/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as QueueIndexRouteImport } from './routes/queue.index'
import { Route as QueueIncidentIdRouteImport } from './routes/queue.$incidentId'
import { Route as TicketKeyRouteImport } from './routes/ticket.$key'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueueRoute,
} as any)
const QueueIncidentIdRoute = QueueIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => QueueRoute,
} as any)
const TicketKeyRoute = TicketKeyRouteImport.update({
  id: '/ticket/$key',
  path: '/ticket/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/evals': typeof EvalsRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/queue': typeof QueueRouteWithChildren
  '/sources': typeof SourcesRoute
  '/tickets': typeof TicketsRoute
  '/queue/$incidentId': typeof QueueIncidentIdRoute
  '/ticket/$key': typeof TicketKeyRoute
  '/queue/': typeof QueueIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/evals': typeof EvalsRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/sources': typeof SourcesRoute
  '/tickets': typeof TicketsRoute
  '/queue/$incidentId': typeof QueueIncidentIdRoute
  '/ticket/$key': typeof TicketKeyRoute
  '/queue': typeof QueueIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/evals': typeof EvalsRoute
  '/guide': typeof GuideRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/queue': typeof QueueRouteWithChildren
  '/sources': typeof SourcesRoute
  '/tickets': typeof TicketsRoute
  '/queue/$incidentId': typeof QueueIncidentIdRoute
  '/ticket/$key': typeof TicketKeyRoute
  '/queue/': typeof QueueIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/evals'
    | '/guide'
    | '/inbox'
    | '/login'
    | '/mobile'
    | '/queue'
    | '/sources'
    | '/tickets'
    | '/queue/$incidentId'
    | '/ticket/$key'
    | '/queue/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/evals'
    | '/guide'
    | '/inbox'
    | '/login'
    | '/mobile'
    | '/sources'
    | '/tickets'
    | '/queue/$incidentId'
    | '/ticket/$key'
    | '/queue'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/evals'
    | '/guide'
    | '/inbox'
    | '/login'
    | '/mobile'
    | '/queue'
    | '/sources'
    | '/tickets'
    | '/queue/$incidentId'
    | '/ticket/$key'
    | '/queue/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  EvalsRoute: typeof EvalsRoute
  GuideRoute: typeof GuideRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MobileRoute: typeof MobileRoute
  QueueRoute: typeof QueueRouteWithChildren
  SourcesRoute: typeof SourcesRoute
  TicketsRoute: typeof TicketsRoute
  TicketKeyRoute: typeof TicketKeyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof QueueRoute
    }
    '/queue/$incidentId': {
      id: '/queue/$incidentId'
      path: '/$incidentId'
      fullPath: '/queue/$incidentId'
      preLoaderRoute: typeof QueueIncidentIdRouteImport
      parentRoute: typeof QueueRoute
    }
    '/ticket/$key': {
      id: '/ticket/$key'
      path: '/ticket/$key'
      fullPath: '/ticket/$key'
      preLoaderRoute: typeof TicketKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QueueRouteChildren {
  QueueIncidentIdRoute: typeof QueueIncidentIdRoute
  QueueIndexRoute: typeof QueueIndexRoute
}

const QueueRouteChildren: QueueRouteChildren = {
  QueueIncidentIdRoute: QueueIncidentIdRoute,
  QueueIndexRoute: QueueIndexRoute,
}

const QueueRouteWithChildren = QueueRoute._addFileChildren(QueueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  EvalsRoute: EvalsRoute,
  GuideRoute: GuideRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MobileRoute: MobileRoute,
  QueueRoute: QueueRouteWithChildren,
  SourcesRoute: SourcesRoute,
  TicketsRoute: TicketsRoute,
  TicketKeyRoute: TicketKeyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
